timevars:
  dt: 0.01
  tstart: 0.0
  tend: 100.0
uservars:
  gamma: 0.5
  tau: 0.5
  mu: 0.5
  beta: 0.5
  prob: 0.5
  alpha: 0.5
  delta: 0.5
  pi: 0.5
  sigma: 0.5
  chi: 0.5
initvars:
  x: 0.5
  y: 0.5
  z: 0.5
  a: 0.5
adaptvars:
  dtpassmin: 0.1
  dtfailmax: 0.5
  dtfailmin: 0.01
  s: 0.9
  rtol: 1.0e-08
  atol: 1.0e-08
  maxsteps: 2000
  maxfail: 60
  dtpassmax: 5.0


